FROM node:23

WORKDIR /app

# RUN apk add --no-cache libc6-compat

COPY package*.json ./

RUN npm ci
RUN npm i lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu sass-embedded-linux-x64
COPY . .

EXPOSE 3000

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev"]
