"""empty message

Revision ID: 5cfdb1de77b6
Revises: 8d032e1a612c
Create Date: 2025-05-21 16:38:41.534118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cfdb1de77b6'
down_revision: Union[str, None] = '8d032e1a612c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrete_column_chart_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['file_columns.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['id'], ['views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discrete_column_chart_views')
    # ### end Alembic commands ###
