"""empty message

Revision ID: f93b5761b23f
Revises: 113e99625059
Create Date: 2025-05-28 11:55:40.256977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93b5761b23f'
down_revision: Union[str, None] = '113e99625059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discrete_column_chart_views_file_id_fkey', 'discrete_column_chart_views', type_='foreignkey')
    op.drop_column('discrete_column_chart_views', 'file_id')
    op.add_column('simple_table_views', sa.Column('filter_model', sa.JSON(), nullable=True))
    op.add_column('simple_table_views', sa.Column('sort_model', sa.JSON(), nullable=True))
    op.drop_constraint('simple_table_views_file_id_fkey', 'simple_table_views', type_='foreignkey')
    op.drop_column('simple_table_views', 'file_id')
    op.add_column('views', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'views', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'views', type_='foreignkey')
    op.drop_column('views', 'file_id')
    op.add_column('simple_table_views', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('simple_table_views_file_id_fkey', 'simple_table_views', 'files', ['file_id'], ['id'])
    op.drop_column('simple_table_views', 'sort_model')
    op.drop_column('simple_table_views', 'filter_model')
    op.add_column('discrete_column_chart_views', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('discrete_column_chart_views_file_id_fkey', 'discrete_column_chart_views', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
